### ISSUE TITLE
"Failed to get a new native library instance" when running project using VLC installed from snap, but installing from apt works fine

### ISSUE THREAD

**Issue by iamphonghg** [caprica/vlcj-javafx-demo#46]
I am building javafx application to play video from rtsp server.
At first I was getting the error "Failed to get a new native library instance" when launching the video on local. Then I found the cause was because I was using VLC install from snap, then I installed the version from apt. Running the video on local worked fine and the error went away.
Then I tried to launch the video from the rtsp link and got an error like "satip error: Failed to setup RTSP session", and I found out that the VLC version installed from apt doesn't support rtsp stream.
Here is the article link: https://askubuntu.com/questions/1360613/unable-to-play-any-rtsp-streams-in-xubuntu-and-debian
This is the error I get when I launch this project using VLC from snap. But if I change to apt version, it won't error anymore:
```
Exception in Application constructor
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:465)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:364)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1071)
Caused by: java.lang.RuntimeException: Unable to construct Application instance: class client.main.Trash.TestVlc
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:891)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:803)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:290)
	... 1 more
Caused by: java.lang.RuntimeException: Failed to get a new native library instance
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.newLibVlcInstance(MediaPlayerFactory.java:225)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:121)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:174)
	at client.main.Trash.TestVlc.<init>(TestVlc.java:29)
	... 14 more
Exception running application client.main.Trash.TestVlc
```
Wow, it took me all day to figure out how to stream rtsp in javafx and now I'm stuck with this weird thing.
Hope to hear from you soon. Hopefully there is a way to be able to use the snap version of VLC.

**Comment by caprica** [comment]
Installing from snap does not install the libvlc native libraries "properly", so vlcj doesn't know where to find them.

You need to look at vlcj's native discovery - you might have to write your own native discovery provider or at least write a DiscoveryDirectoryProvider to tell vlcj where it can get those native libraries from.

Read the Javadoc on those topics, or have a look at the source code for the existing native discovery implementations to give you an idea.

**Comment by iamphonghg** [comment]
@caprica Thanks for your answer, this seems to be too hard for me.

**Comment by caprica** [comment]
It is actually pretty easy. You just need to put the work in.

https://caprica.github.io/vlcj/javadoc/4.7.0/uk/co/caprica/vlcj/factory/discovery/NativeDiscovery.html
https://caprica.github.io/vlcj/javadoc/4.7.0/uk/co/caprica/vlcj/factory/discovery/provider/DiscoveryDirectoryProvider.html
https://caprica.github.io/vlcj/javadoc/4.7.0/uk/co/caprica/vlcj/factory/discovery/provider/DirectoryProviderDiscoveryStrategy.html

etc.

**Comment by iamphonghg** [comment]
Can you explain a bit more detailed, how would i write more code, and where to put it? I'm sorry if I bother you, but I really don't know where to start. This is the key point for me to finish my big assignment.

**Comment by caprica** [comment]
Write a new implementation of a DiscoveryDirectoryProvider, following the instructions in the Javadoc links I gave above.

Your implementation needs to return the directory name of the place where your snap package installs the libvlc native libraries.

You *may* (it might work without it) also need to set VLC_PLUGIN_PATH environment variable in a shell script file used to launch your application. This needs to point to the "plugins" directory that your snap package installs when it installs the VLC libraries.

I have never personally used a snap package to install a vlcj project so I can't help any more than that. Personally, I use the OS native dependency management solution to install packages, so I create a package for my vlcj project that depends on libvlc, and everything just works.

Maybe simpler, look at UserDirConfigFileDiscoveryDirectoryProvider. This should actually work out of the box. Instead of doing the above, all you need to do is create a file named vlcj.config and put it in the "current" directory where your Java app runs from. That config file should look like this:

```
nativeDirectory=/the/path/where/libvlc/is/installed
```

Replace the path obviously.

If this doesn't work for you, I can't help you further - like I said, I never used vlcj and libvlc with snap.

**Comment by iamphonghg** [comment]
I just tried implementing DiscoveryDirectoryProvider like this. Now how can I do something like launch it?
```
package uk.co.caprica.vlcj.javafx.demo;

import uk.co.caprica.vlcj.factory.discovery.provider.DiscoveryDirectoryProvider;

public class VlcNativeLib implements DiscoveryDirectoryProvider {
  @Override
  public int priority() {
    return 0;
  }

  @Override
  public String[] directories() {
    return new String[]{"/usr/lib/x86_64-linux-gnu/libvlc.so"};
  }

  @Override
  public boolean supported() {
    return true;
  }
}
```

**Comment by caprica** [comment]
You need to use the "service provider" mechanism, which essentially means adding a META-INF/services directory with an appropriately configured services file.

e.g.
```
META-INF/services/uk.co.caprica.vlcj.factory.discovery.provider.DiscoveryDirectoryProvider
```
And that file should contain the fully-qualified-name of your class.

It's explained in the Javadoc.

**Comment by caprica** [comment]
I would also give your implementation a priority of `INTEGER.MAX_VALUE`.

**Comment by iamphonghg** [comment]
Sorry, I really don't understand the "service provider" mechanism as you said above. I tried creating vlcj.config file inside /home/user/.config/vlcj directory but it didn't work.
Maybe I need a detail on how to implement as you mentioned above. Could you please help me?
